#!/bin/sh

open "/Applications/GyazMail.app"
open "/Applications/Slack.app"

# The following is from an answer by Jacques Rioux in an Apple discussion forum:
# https://discussions.apple.com/thread/7520296?start=0&tstart=0

defaults -currentHost write com.apple.notificationcenterui doNotDisturb -bool FALSE
defaults -currentHost delete com.apple.notificationcenterui doNotDisturbDate
osascript -e 'quit application "Notification Center"'
killall usernoted

# When this script is executed from Quicksilver, Terminal doesn't close its
# window for some reason, even if you configure Terminal to turn off the
# "restore text" feature (in the Profile -> Window tab) and set the "when the
# shell exits" to "close the window" (in the Profile -> Shell tab).  So:
osascript -e 'tell application "Terminal" to quit'
