#!/bin/csh
#
# This is a script to start Aquamacs by issuing a command from within
# Quicksilver. This is necessary because simply starting Aquamacs directly
# from Quicksilver fails to set the full environment, particularly the
# environment variables I normally set in shells.
#
# It is annoyingly hard to make Terminal close its windows after it starts
# up, and also not create new windows every time this script is executed.  It
# turns out that configuring Terminal to turn off the "restore text" feature
# (in the Profile -> Window tab) and to set the "when the shell exits" to
# "close the window" (in the Profile -> Shell tab) is *not* enough to make
# Terminal close its window after this script is executed.  Nor is it enough
# to issue this command in a shell:
#     defaults write com.apple.Terminal NSQuitAlwaysKeepsWindows -bool false
# I finally added an explicit command via osascript to tell Terminal to quit.

rm -f ~/Library/Application\ Support/Aquamacs\ Emacs/tramp
nohup open /Applications/Aquamacs\ 2.4/Aquamacs.app 
osascript -e 'tell application "Terminal" to quit'
