#!/bin/sh
# =============================================================================
# @file    mac-low-power
# @brief   Turn off inessential processes to conserve laptop battery
# @author  Michael Hucka (mhucka@caltech.edu), Caltech
# =============================================================================
#
# Certain things like the bluetooth transceiver, Skype, Dropbox, and other
# programs and processes may as well be turned off when you're not connected
# to a network and not using your usual desktop hardware.  I do this to save
# the battery when flying on airplanes.
#
# to do:
# - set a list variable for the killall's and do a loop
# - have a directory of scripts to execute, for things like a gyazmail applescript

# Turn off bluetooth.
blueutil off

# Turn off wifi
networksetup -setairportpower en0 off

# Random programs
killall Twitter
killall Cobook
killall Cloud
killall Skype
killall Messages
killall Dropbox
killall DisplayPad
killall "Stack Exchange Notifier"
killall "RSS Menu"
killall "I'm Away"
killall Multimon
killall PivotalBooster
killall "Day One Reminders"
killall "SplashID Safe"
killall "CrashPlan menu bar"
killall MouseLocatorAgent
killall Synergy
killall PandaBar
killall Boom
killall Committed
killall PowerMate
killall "Display Menu"
killall "1Password 4"
killall "properVOLUME"
# spt pause

# Remind me to pause CrashPlan using the menubar utility.
osascript -e 'tell app "System Events" to display dialog "Pause CrashPlan\""'

# Remind me to put Gyazmail into offline mode.
osascript -e 'tell app "System Events" to display dialog "Turn off gyazmail option \"Check for new messages in all folders\""'
