#!/bin/sh
# Show processes listening on ports.
#
# Usage:
#   ports [<options>]
# Any <options> are passed to lsof.
#
# Copyright 2024 Michael Hucka.
# License: MIT License – see file "LICENSE" in the project website.
# Website: https://github.com/mhucka/small-scripts

set -e

test "$1" = "--help" && {
    grep ^#/ <"$0"| cut -c4-
    exit 2
}

exec lsof -iTCP -sTCP:LISTEN -P "$@"
